export let products = [
  {
    id: 1,
    title: "Nike",
    price: 100000,
    stock: 6,
    model: "Air Jordan Mid 1",
    description:
      "Inspirada en el AJ1 original, esta edición de corte mid mantiene el look icónico que te encanta, y los colores selectos y el cuero impecable le dan una identidad distintiva.",
    category: "urbanas",
    img: "https://res.cloudinary.com/djnzf670x/image/upload/v1696440016/air_jordan_1_mid_cdz9ay.webp",
  },
  {
    id: 2,
    title: "Puma",
    price: 70000,
    stock: 4,
    model: "Magnify Nitro",
    description: "",
    category: "deportivas",
    img: "https://res.cloudinary.com/djnzf670x/image/upload/v1696440033/puma_magnify_nito_wwxxoy.avif",
  },
  {
    id: 3,
    title: "Adidas",
    price: 80000,
    stock: 5,
    model: "Racer TR21",
    description: "",
    category: "deportivas",
    img: "https://res.cloudinary.com/djnzf670x/image/upload/v1696440033/adidas_racer_tr21_esvyso.avif",
  },
  {
    id: 4,
    title: "New Balance",
    price: 60000,
    stock: 7,
    model: "574",
    description: "",
    category: "urbanas",
    img: "https://res.cloudinary.com/djnzf670x/image/upload/v1696440598/zapatillas-hombre-new-balance-574-ml574lgi-1_1_lrkt8j.jpg",
  },
];
